spring:
  application:
    name: orderingapp

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/ordering_app
    username: root
    password: MySQL0781172951
    driver-class-name: com.mysql.cj.jdbc.Driver


  # Server port
server:
  port: 9090

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      apache:
        tomcat: DEBUG
    root: INFO